package com.mybatis.entity;

public class Employee {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employee.id
	 *
	 * @mbg.generated Thu Mar 21 14:45:14 CST 2019
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employee.last_name
	 *
	 * @mbg.generated Thu Mar 21 14:45:14 CST 2019
	 */
	private String lastName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employee.gender
	 *
	 * @mbg.generated Thu Mar 21 14:45:14 CST 2019
	 */
	private Integer gender;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employee.email
	 *
	 * @mbg.generated Thu Mar 21 14:45:14 CST 2019
	 */
	private String email;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employee.dept_id
	 *
	 * @mbg.generated Thu Mar 21 14:45:14 CST 2019
	 */
	private Integer deptId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employee.id
	 *
	 * @return the value of employee.id
	 *
	 * @mbg.generated Thu Mar 21 14:45:14 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employee.id
	 *
	 * @param id the value for employee.id
	 *
	 * @mbg.generated Thu Mar 21 14:45:14 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employee.last_name
	 *
	 * @return the value of employee.last_name
	 *
	 * @mbg.generated Thu Mar 21 14:45:14 CST 2019
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employee.last_name
	 *
	 * @param lastName the value for employee.last_name
	 *
	 * @mbg.generated Thu Mar 21 14:45:14 CST 2019
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName == null ? null : lastName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employee.gender
	 *
	 * @return the value of employee.gender
	 *
	 * @mbg.generated Thu Mar 21 14:45:14 CST 2019
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employee.gender
	 *
	 * @param gender the value for employee.gender
	 *
	 * @mbg.generated Thu Mar 21 14:45:14 CST 2019
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employee.email
	 *
	 * @return the value of employee.email
	 *
	 * @mbg.generated Thu Mar 21 14:45:14 CST 2019
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employee.email
	 *
	 * @param email the value for employee.email
	 *
	 * @mbg.generated Thu Mar 21 14:45:14 CST 2019
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employee.dept_id
	 *
	 * @return the value of employee.dept_id
	 *
	 * @mbg.generated Thu Mar 21 14:45:14 CST 2019
	 */
	public Integer getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employee.dept_id
	 *
	 * @param deptId the value for employee.dept_id
	 *
	 * @mbg.generated Thu Mar 21 14:45:14 CST 2019
	 */
	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	@Override
	public String toString() {
		return "Employee [id=" + id + ", lastName=" + lastName + ", gender=" + gender + ", email=" + email + ", deptId="
				+ deptId + "]";
	}
}